version: '3.9'

services:
   db:
     image: postgres
     volumes:
       - ./data/db:/var/lib/postgresql/data
     enviroment:
       - POSTGRES_DB=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
   web:
      build: .
      command: python manage.py runserver 1.1.1.1:8888
      volumes:
        - .:/code
      ports:
        - '8888:8888'
      depends_on:
        - db 


